package com.example.lesson8project.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF6D4C41)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFD7CCC8)
val md_theme_light_onPrimaryContainer = Color(0xFF281814)
val md_theme_light_secondary = Color(0xFF5D4037)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFEFEBE9)
val md_theme_light_onSecondaryContainer = Color(0xFF1E110F)
val md_theme_light_background = Color(0xFFFFF8E1)
val md_theme_light_onBackground = Color(0xFF1F1B16)
val md_theme_light_surface = Color(0xFFFFF8E1)
val md_theme_light_onSurface = Color(0xFF1F1B16)
val md_theme_light_surfaceVariant = Color(0xFFE7E0D1)
val md_theme_light_onSurfaceVariant = Color(0xFF49454F)

val md_theme_dark_primary = Color(0xFFFFCA28)
val md_theme_dark_onPrimary = Color(0xFF422F00)
val md_theme_dark_primaryContainer = Color(0xFF5E4402)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFEFA6)
val md_theme_dark_secondary = Color(0xFFD7CCC8)
val md_theme_dark_onSecondary = Color(0xFF3E2C28)
val md_theme_dark_secondaryContainer = Color(0xFF563F3A)
val md_theme_dark_onSecondaryContainer = Color(0xFFF2DDB7)
val md_theme_dark_background = Color(0xFF121212)
val md_theme_dark_onBackground = Color(0xFFE2E2E2)
val md_theme_dark_surface = Color(0xFF1E1E1E)
val md_theme_dark_onSurface = Color(0xFFE2E2E2)
val md_theme_dark_surfaceVariant = Color(0xFF2C2C2C)
val md_theme_dark_onSurfaceVariant = Color(0xFFCAC4D0)
